// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IM.Login.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_IM_2eLogin_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_IM_2eLogin_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3014000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3014000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "IM.Base.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_IM_2eLogin_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_IM_2eLogin_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_IM_2eLogin_2eproto;
namespace IM {
namespace Login {
class UserLoginRq;
class UserLoginRqDefaultTypeInternal;
extern UserLoginRqDefaultTypeInternal _UserLoginRq_default_instance_;
}  // namespace Login
}  // namespace IM
PROTOBUF_NAMESPACE_OPEN
template<> ::IM::Login::UserLoginRq* Arena::CreateMaybeMessage<::IM::Login::UserLoginRq>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace IM {
namespace Login {

// ===================================================================

class UserLoginRq PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:IM.Login.UserLoginRq) */ {
 public:
  inline UserLoginRq() : UserLoginRq(nullptr) {}
  virtual ~UserLoginRq();

  UserLoginRq(const UserLoginRq& from);
  UserLoginRq(UserLoginRq&& from) noexcept
    : UserLoginRq() {
    *this = ::std::move(from);
  }

  inline UserLoginRq& operator=(const UserLoginRq& from) {
    CopyFrom(from);
    return *this;
  }
  inline UserLoginRq& operator=(UserLoginRq&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const UserLoginRq& default_instance();

  static inline const UserLoginRq* internal_default_instance() {
    return reinterpret_cast<const UserLoginRq*>(
               &_UserLoginRq_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(UserLoginRq& a, UserLoginRq& b) {
    a.Swap(&b);
  }
  inline void Swap(UserLoginRq* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(UserLoginRq* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline UserLoginRq* New() const final {
    return CreateMaybeMessage<UserLoginRq>(nullptr);
  }

  UserLoginRq* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<UserLoginRq>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const UserLoginRq& from);
  void MergeFrom(const UserLoginRq& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(UserLoginRq* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "IM.Login.UserLoginRq";
  }
  protected:
  explicit UserLoginRq(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_IM_2eLogin_2eproto);
    return ::descriptor_table_IM_2eLogin_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIdFieldNumber = 1,
    kPasswordFieldNumber = 2,
    kUserStatusFieldNumber = 3,
    kClientTypeFieldNumber = 4,
  };
  // string id = 1;
  void clear_id();
  const std::string& id() const;
  void set_id(const std::string& value);
  void set_id(std::string&& value);
  void set_id(const char* value);
  void set_id(const char* value, size_t size);
  std::string* mutable_id();
  std::string* release_id();
  void set_allocated_id(std::string* id);
  private:
  const std::string& _internal_id() const;
  void _internal_set_id(const std::string& value);
  std::string* _internal_mutable_id();
  public:

  // string password = 2;
  void clear_password();
  const std::string& password() const;
  void set_password(const std::string& value);
  void set_password(std::string&& value);
  void set_password(const char* value);
  void set_password(const char* value, size_t size);
  std::string* mutable_password();
  std::string* release_password();
  void set_allocated_password(std::string* password);
  private:
  const std::string& _internal_password() const;
  void _internal_set_password(const std::string& value);
  std::string* _internal_mutable_password();
  public:

  // .IM.Base.UserStatus user_status = 3;
  void clear_user_status();
  ::IM::Base::UserStatus user_status() const;
  void set_user_status(::IM::Base::UserStatus value);
  private:
  ::IM::Base::UserStatus _internal_user_status() const;
  void _internal_set_user_status(::IM::Base::UserStatus value);
  public:

  // .IM.Base.ClientType client_type = 4;
  void clear_client_type();
  ::IM::Base::ClientType client_type() const;
  void set_client_type(::IM::Base::ClientType value);
  private:
  ::IM::Base::ClientType _internal_client_type() const;
  void _internal_set_client_type(::IM::Base::ClientType value);
  public:

  // @@protoc_insertion_point(class_scope:IM.Login.UserLoginRq)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr id_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr password_;
  int user_status_;
  int client_type_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_IM_2eLogin_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// UserLoginRq

// string id = 1;
inline void UserLoginRq::clear_id() {
  id_.ClearToEmpty();
}
inline const std::string& UserLoginRq::id() const {
  // @@protoc_insertion_point(field_get:IM.Login.UserLoginRq.id)
  return _internal_id();
}
inline void UserLoginRq::set_id(const std::string& value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:IM.Login.UserLoginRq.id)
}
inline std::string* UserLoginRq::mutable_id() {
  // @@protoc_insertion_point(field_mutable:IM.Login.UserLoginRq.id)
  return _internal_mutable_id();
}
inline const std::string& UserLoginRq::_internal_id() const {
  return id_.Get();
}
inline void UserLoginRq::_internal_set_id(const std::string& value) {
  
  id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void UserLoginRq::set_id(std::string&& value) {
  
  id_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:IM.Login.UserLoginRq.id)
}
inline void UserLoginRq::set_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:IM.Login.UserLoginRq.id)
}
inline void UserLoginRq::set_id(const char* value,
    size_t size) {
  
  id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:IM.Login.UserLoginRq.id)
}
inline std::string* UserLoginRq::_internal_mutable_id() {
  
  return id_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* UserLoginRq::release_id() {
  // @@protoc_insertion_point(field_release:IM.Login.UserLoginRq.id)
  return id_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void UserLoginRq::set_allocated_id(std::string* id) {
  if (id != nullptr) {
    
  } else {
    
  }
  id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), id,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:IM.Login.UserLoginRq.id)
}

// string password = 2;
inline void UserLoginRq::clear_password() {
  password_.ClearToEmpty();
}
inline const std::string& UserLoginRq::password() const {
  // @@protoc_insertion_point(field_get:IM.Login.UserLoginRq.password)
  return _internal_password();
}
inline void UserLoginRq::set_password(const std::string& value) {
  _internal_set_password(value);
  // @@protoc_insertion_point(field_set:IM.Login.UserLoginRq.password)
}
inline std::string* UserLoginRq::mutable_password() {
  // @@protoc_insertion_point(field_mutable:IM.Login.UserLoginRq.password)
  return _internal_mutable_password();
}
inline const std::string& UserLoginRq::_internal_password() const {
  return password_.Get();
}
inline void UserLoginRq::_internal_set_password(const std::string& value) {
  
  password_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void UserLoginRq::set_password(std::string&& value) {
  
  password_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:IM.Login.UserLoginRq.password)
}
inline void UserLoginRq::set_password(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  password_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:IM.Login.UserLoginRq.password)
}
inline void UserLoginRq::set_password(const char* value,
    size_t size) {
  
  password_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:IM.Login.UserLoginRq.password)
}
inline std::string* UserLoginRq::_internal_mutable_password() {
  
  return password_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* UserLoginRq::release_password() {
  // @@protoc_insertion_point(field_release:IM.Login.UserLoginRq.password)
  return password_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void UserLoginRq::set_allocated_password(std::string* password) {
  if (password != nullptr) {
    
  } else {
    
  }
  password_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), password,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:IM.Login.UserLoginRq.password)
}

// .IM.Base.UserStatus user_status = 3;
inline void UserLoginRq::clear_user_status() {
  user_status_ = 0;
}
inline ::IM::Base::UserStatus UserLoginRq::_internal_user_status() const {
  return static_cast< ::IM::Base::UserStatus >(user_status_);
}
inline ::IM::Base::UserStatus UserLoginRq::user_status() const {
  // @@protoc_insertion_point(field_get:IM.Login.UserLoginRq.user_status)
  return _internal_user_status();
}
inline void UserLoginRq::_internal_set_user_status(::IM::Base::UserStatus value) {
  
  user_status_ = value;
}
inline void UserLoginRq::set_user_status(::IM::Base::UserStatus value) {
  _internal_set_user_status(value);
  // @@protoc_insertion_point(field_set:IM.Login.UserLoginRq.user_status)
}

// .IM.Base.ClientType client_type = 4;
inline void UserLoginRq::clear_client_type() {
  client_type_ = 0;
}
inline ::IM::Base::ClientType UserLoginRq::_internal_client_type() const {
  return static_cast< ::IM::Base::ClientType >(client_type_);
}
inline ::IM::Base::ClientType UserLoginRq::client_type() const {
  // @@protoc_insertion_point(field_get:IM.Login.UserLoginRq.client_type)
  return _internal_client_type();
}
inline void UserLoginRq::_internal_set_client_type(::IM::Base::ClientType value) {
  
  client_type_ = value;
}
inline void UserLoginRq::set_client_type(::IM::Base::ClientType value) {
  _internal_set_client_type(value);
  // @@protoc_insertion_point(field_set:IM.Login.UserLoginRq.client_type)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace Login
}  // namespace IM

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_IM_2eLogin_2eproto
